const ROUTER_PATHS = {
  MAIN_PAGE: '/',
  LOGIN_MAIN: '/login-main',
  LOGIN_KAKAO: '/login-kakao',
  LOGIN_NAVER: '/login-naver',
  JOIN: '/join',
  MEMBER_DATA_ENTRY: '/member-data-entry',
  JOB_MAIN: '/job',
  COMMUNITY: '/community',
  USER_POST: '/user-post/:nickname/posts',
  WRITE_COMMUNITY_POST: '/community/post',
  COMMUNITY_POST_DETAIL: '/community/post/:id',
  WRITE_RECRUITMENT_POST: '/job/recruitment/post',
  WRITE_JOB_SEARCH_POST: '/job/job-search/post',
  JOB_SEARCH_POST_EDIT: '/job/job-seek/edit/:id',
  JOB_SEARCH_POST_DETAIL: '/job/job-seek/post/:id',
  RECRUITMENT_POST_DETAIL: '/job/recruitment/post/:id',
  RECRUITMENT_POST_EDIT: '/job/recruitment/edit/:id',
  FIND_ID: '/find/id',
  FIND_ID_COMPLETE_PAGE: '/find/id/complete-page',
  FIND_PW: '/find/pw',
  FIND_PW_CHECK_ID_PAGE: '/find/pw/check-id-page',
  FIND_PW_CHANGE_PW: '/find/pw/change-pw',
  MY_PAGE: '/my-page',
  MY_EDIT_PROFILE: '/my-page/edit-profile',
  MY_EDIT_PW: '/my-page/edit-password',
  MY_PW_MIS: '/my-page/password-mis',
  MY_SCRAP: '/my-page/my-scrap',
  MY_POST: '/my-page/my-post',
  MY_RECENT_LIST: '/my-page/my-recent-list',
  MY_DRAFTS: '/my-page/my-drafts',
  ERROR: '/error',
  SERVER_ERROR: '/server-error',
  KAKAO_SUCCESS: '/login/kakao/success',
  NAVER_SUCCESS: '/login/naver/success',
  TERMS_OF_SERVICE: '/terms-of-service',
  PRIVACY_POLICY: '/privacy-policy',
  INSTALL_METHOD: '/install-method',
}

export default ROUTER_PATHS
