name: Deploy Vite app to Vercel (Yarn + Lighthouse)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build Vite project
        run: yarn build

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --name bookjob --yes

      - name: Run Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: https://bookjob.vercel.app
          configPath: ./lighthouserc.json
