name: 'Chromatic'

on: push

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 모든 Git 히스토리를 가져옴 (Chromatic이 변경사항을 감지하는 데 필요)

      - uses: actions/setup-node@v4
        with:
          node-version: 18 # Yarn과 호환성이 좋은 LTS 버전

      - name: Install dependencies
        run: yarn install --frozen-lockfile # Yarn을 사용하는 경우 적절한 설치 방식

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
