name: 'Chromatic'

on:
  push:
    branches:
      - main
      - develop  # main, develop 브랜치에서만 실행

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-22.04  # 최신 안정적인 환경 사용
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'  # Yarn 캐시 활성화

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 100000

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}